spring:
  application:
    name: 'lupang-commerce-user'
  datasource:
    url: jdbc:mysql://localhost:3306/lupang_schema
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379

coolsms:
  apikey: ${COOLSMS_API_KEY}
  apisecret: ${COOLSMS_API_SECRET}
  baseurl: https://api.coolsm.co.kr
  from:
    number: ${FROM_PHONE_NUMBER}

aes:
  key: abcdefghabcdefgh
  iv: 0123456789abcdef
  algorithms: AES/CBC/PKCS5Padding