spring:
  application:
    name: 'lupang-commerce-admin'
  datasource:
    url: jdbc:mysql://mysql:3306/lupang-database
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
